#include <lcom/lcf.h>

xpm_row_t const Explosion_1_xpm[] = {
"40 40 32 1",
" 	c None",
".	c #ECD351",
"+	c #F8D14E",
"@	c #F8EBB2",
"#	c #FAE07D",
"$	c #EBD25F",
"%	c #F6F0BE",
"&	c #F5EA9A",
"*	c #F5F3AA",
"=	c #F7F295",
"-	c #F0DC62",
";	c #F7E283",
">	c #FAE6BE",
",	c #E4CD35",
"'	c #F9E486",
")	c #FDF2B9",
"!	c #FDFDE3",
"~	c #EBDA60",
"{	c #E1CC61",
"]	c #FEEDC9",
"^	c #EFD74E",
"/	c #EFD755",
"(	c #FEF6AE",
"_	c #FCF6C0",
":	c #FBF5CF",
"<	c #EADA8E",
"[	c #F1D665",
"}	c #FAEA81",
"|	c #FAFAC9",
"1	c #F7EFB4",
"2	c #EFC62E",
"3	c #F9EBAD",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                  .+                    ",
"                  @#$%                  ",
"                 &*=-;>                 ",
"                 ,')!~{                 ",
"                 ]^/(_:                 ",
"                  <[}|                  ",
"                   123                  ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        ",
"                                        "};
